// Code generated by pigeon; DO NOT EDIT.

package ng_operand // Changed package name

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/HobbyOSs/gosk/internal/ast" // ast パッケージをインポート
	"github.com/morikuni/failure"
	// cpu パッケージは不要
)

// --- Helper functions ---
func toInt(s string) int64 {
	// 10進数または16進数をパース
	if strings.HasPrefix(s, "0x") || strings.HasPrefix(s, "0X") {
		v, _ := strconv.ParseInt(s[2:], 16, 64)
		return v
	}
	v, _ := strconv.ParseInt(s, 10, 64)
	return v
}

func isHex(s string) bool {
	return strings.HasPrefix(s, "0x") || strings.HasPrefix(s, "0X")
}

// getRegisterType と getImmediateSizeType は operand_types.go で定義想定
// ... 他のヘルパー関数 ...

var g = &grammar{
	rules: []*rule{
		{
			name: "OperandString",
			pos:  position{line: 35, col: 1, offset: 805},
			expr: &actionExpr{
				pos: position{line: 35, col: 18, offset: 822},
				run: (*parser).callonOperandString1,
				expr: &seqExpr{
					pos: position{line: 35, col: 18, offset: 822},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 35, col: 18, offset: 822},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 35, col: 20, offset: 824},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 35, col: 23, offset: 827},
								name: "Operand",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 35, col: 31, offset: 835},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 35, col: 33, offset: 837},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Operand",
			pos:  position{line: 42, col: 1, offset: 1028},
			expr: &choiceExpr{
				pos: position{line: 42, col: 12, offset: 1039},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 42, col: 12, offset: 1039},
						name: "MemoryAddress",
					},
					&ruleRefExpr{
						pos:  position{line: 42, col: 28, offset: 1055},
						name: "Register",
					},
					&ruleRefExpr{
						pos:  position{line: 42, col: 39, offset: 1066},
						name: "Immediate",
					},
					&ruleRefExpr{
						pos:  position{line: 42, col: 51, offset: 1078},
						name: "Label",
					},
					&ruleRefExpr{
						pos:  position{line: 42, col: 59, offset: 1086},
						name: "SegmentRegister",
					},
				},
			},
		},
		{
			name: "MemoryAddress",
			pos:  position{line: 46, col: 1, offset: 1216},
			expr: &actionExpr{
				pos: position{line: 46, col: 18, offset: 1233},
				run: (*parser).callonMemoryAddress1,
				expr: &seqExpr{
					pos: position{line: 46, col: 18, offset: 1233},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 46, col: 18, offset: 1233},
							label: "dt",
							expr: &zeroOrOneExpr{
								pos: position{line: 46, col: 21, offset: 1236},
								expr: &ruleRefExpr{
									pos:  position{line: 46, col: 21, offset: 1236},
									name: "DataType",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 31, offset: 1246},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 33, offset: 1248},
							label: "jt",
							expr: &zeroOrOneExpr{
								pos: position{line: 46, col: 36, offset: 1251},
								expr: &ruleRefExpr{
									pos:  position{line: 46, col: 36, offset: 1251},
									name: "JumpType",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 46, offset: 1261},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 48, offset: 1263},
							label: "seg",
							expr: &zeroOrOneExpr{
								pos: position{line: 46, col: 52, offset: 1267},
								expr: &seqExpr{
									pos: position{line: 46, col: 53, offset: 1268},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 46, col: 53, offset: 1268},
											name: "SegmentRegisterName",
										},
										&ruleRefExpr{
											pos:  position{line: 46, col: 73, offset: 1288},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 46, col: 75, offset: 1290},
											val:        ":",
											ignoreCase: false,
											want:       "\":\"",
										},
										&ruleRefExpr{
											pos:  position{line: 46, col: 79, offset: 1294},
											name: "_",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 46, col: 83, offset: 1298},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 87, offset: 1302},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 89, offset: 1304},
							label: "body",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 94, offset: 1309},
								name: "MemoryBody",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 105, offset: 1320},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 46, col: 107, offset: 1322},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "MemoryBody",
			pos:  position{line: 72, col: 1, offset: 2160},
			expr: &choiceExpr{
				pos: position{line: 72, col: 15, offset: 2174},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 72, col: 15, offset: 2174},
						name: "BaseIndexScaleDisp",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 36, offset: 2195},
						name: "BaseIndexDisp",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 52, offset: 2211},
						name: "BaseScaleDisp",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 68, offset: 2227},
						name: "IndexScaleDisp",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 85, offset: 2244},
						name: "BaseDisp",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 96, offset: 2255},
						name: "IndexDisp",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 108, offset: 2267},
						name: "BaseIndex",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 120, offset: 2279},
						name: "BaseOnly",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 131, offset: 2290},
						name: "IndexOnly",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 143, offset: 2302},
						name: "DispOnly",
					},
				},
			},
		},
		{
			name: "BaseIndexScaleDisp",
			pos:  position{line: 75, col: 1, offset: 2391},
			expr: &actionExpr{
				pos: position{line: 75, col: 23, offset: 2413},
				run: (*parser).callonBaseIndexScaleDisp1,
				expr: &seqExpr{
					pos: position{line: 75, col: 23, offset: 2413},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 75, col: 23, offset: 2413},
							label: "base",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 28, offset: 2418},
								name: "RegisterName",
							},
						},
						&labeledExpr{
							pos:   position{line: 75, col: 41, offset: 2431},
							label: "op1",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 45, offset: 2435},
								name: "AddOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 75, col: 51, offset: 2441},
							label: "index",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 57, offset: 2447},
								name: "RegisterName",
							},
						},
						&labeledExpr{
							pos:   position{line: 75, col: 70, offset: 2460},
							label: "scale",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 76, offset: 2466},
								name: "Scale",
							},
						},
						&labeledExpr{
							pos:   position{line: 75, col: 82, offset: 2472},
							label: "op2",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 86, offset: 2476},
								name: "AddOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 75, col: 92, offset: 2482},
							label: "disp",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 97, offset: 2487},
								name: "ImmediateValue",
							},
						},
					},
				},
			},
		},
		{
			name: "BaseIndexDisp",
			pos:  position{line: 85, col: 1, offset: 2977},
			expr: &actionExpr{
				pos: position{line: 85, col: 18, offset: 2994},
				run: (*parser).callonBaseIndexDisp1,
				expr: &seqExpr{
					pos: position{line: 85, col: 18, offset: 2994},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 85, col: 18, offset: 2994},
							label: "base",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 23, offset: 2999},
								name: "RegisterName",
							},
						},
						&labeledExpr{
							pos:   position{line: 85, col: 36, offset: 3012},
							label: "op1",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 40, offset: 3016},
								name: "AddOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 85, col: 46, offset: 3022},
							label: "index",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 52, offset: 3028},
								name: "RegisterName",
							},
						},
						&labeledExpr{
							pos:   position{line: 85, col: 65, offset: 3041},
							label: "op2",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 69, offset: 3045},
								name: "AddOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 85, col: 75, offset: 3051},
							label: "disp",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 80, offset: 3056},
								name: "ImmediateValue",
							},
						},
					},
				},
			},
		},
		{
			name: "BaseScaleDisp",
			pos:  position{line: 94, col: 1, offset: 3483},
			expr: &actionExpr{
				pos: position{line: 94, col: 18, offset: 3500},
				run: (*parser).callonBaseScaleDisp1,
				expr: &seqExpr{
					pos: position{line: 94, col: 18, offset: 3500},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 94, col: 18, offset: 3500},
							label: "base",
							expr: &ruleRefExpr{
								pos:  position{line: 94, col: 23, offset: 3505},
								name: "RegisterName",
							},
						},
						&labeledExpr{
							pos:   position{line: 94, col: 36, offset: 3518},
							label: "op1",
							expr: &ruleRefExpr{
								pos:  position{line: 94, col: 40, offset: 3522},
								name: "AddOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 94, col: 46, offset: 3528},
							label: "index",
							expr: &ruleRefExpr{
								pos:  position{line: 94, col: 52, offset: 3534},
								name: "RegisterName",
							},
						},
						&labeledExpr{
							pos:   position{line: 94, col: 65, offset: 3547},
							label: "scale",
							expr: &ruleRefExpr{
								pos:  position{line: 94, col: 71, offset: 3553},
								name: "Scale",
							},
						},
					},
				},
			},
		},
		{
			name: "IndexScaleDisp",
			pos:  position{line: 100, col: 1, offset: 3826},
			expr: &actionExpr{
				pos: position{line: 100, col: 19, offset: 3844},
				run: (*parser).callonIndexScaleDisp1,
				expr: &seqExpr{
					pos: position{line: 100, col: 19, offset: 3844},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 100, col: 19, offset: 3844},
							label: "index",
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 25, offset: 3850},
								name: "RegisterName",
							},
						},
						&labeledExpr{
							pos:   position{line: 100, col: 38, offset: 3863},
							label: "scale",
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 44, offset: 3869},
								name: "Scale",
							},
						},
						&labeledExpr{
							pos:   position{line: 100, col: 50, offset: 3875},
							label: "op1",
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 54, offset: 3879},
								name: "AddOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 100, col: 60, offset: 3885},
							label: "disp",
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 65, offset: 3890},
								name: "ImmediateValue",
							},
						},
					},
				},
			},
		},
		{
			name: "BaseDisp",
			pos:  position{line: 108, col: 1, offset: 4254},
			expr: &actionExpr{
				pos: position{line: 108, col: 13, offset: 4266},
				run: (*parser).callonBaseDisp1,
				expr: &seqExpr{
					pos: position{line: 108, col: 13, offset: 4266},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 108, col: 13, offset: 4266},
							label: "base",
							expr: &ruleRefExpr{
								pos:  position{line: 108, col: 18, offset: 4271},
								name: "RegisterName",
							},
						},
						&labeledExpr{
							pos:   position{line: 108, col: 31, offset: 4284},
							label: "op1",
							expr: &ruleRefExpr{
								pos:  position{line: 108, col: 35, offset: 4288},
								name: "AddOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 108, col: 41, offset: 4294},
							label: "disp",
							expr: &ruleRefExpr{
								pos:  position{line: 108, col: 46, offset: 4299},
								name: "ImmediateValue",
							},
						},
					},
				},
			},
		},
		{
			name: "IndexDisp",
			pos:  position{line: 115, col: 1, offset: 4586},
			expr: &actionExpr{
				pos: position{line: 115, col: 14, offset: 4599},
				run: (*parser).callonIndexDisp1,
				expr: &seqExpr{
					pos: position{line: 115, col: 14, offset: 4599},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 115, col: 14, offset: 4599},
							label: "index",
							expr: &ruleRefExpr{
								pos:  position{line: 115, col: 20, offset: 4605},
								name: "RegisterName",
							},
						},
						&labeledExpr{
							pos:   position{line: 115, col: 33, offset: 4618},
							label: "op1",
							expr: &ruleRefExpr{
								pos:  position{line: 115, col: 37, offset: 4622},
								name: "AddOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 115, col: 43, offset: 4628},
							label: "disp",
							expr: &ruleRefExpr{
								pos:  position{line: 115, col: 48, offset: 4633},
								name: "ImmediateValue",
							},
						},
					},
				},
			},
		},
		{
			name: "BaseIndex",
			pos:  position{line: 122, col: 1, offset: 4980},
			expr: &actionExpr{
				pos: position{line: 122, col: 14, offset: 4993},
				run: (*parser).callonBaseIndex1,
				expr: &seqExpr{
					pos: position{line: 122, col: 14, offset: 4993},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 122, col: 14, offset: 4993},
							label: "base",
							expr: &ruleRefExpr{
								pos:  position{line: 122, col: 19, offset: 4998},
								name: "RegisterName",
							},
						},
						&labeledExpr{
							pos:   position{line: 122, col: 32, offset: 5011},
							label: "op1",
							expr: &ruleRefExpr{
								pos:  position{line: 122, col: 36, offset: 5015},
								name: "AddOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 122, col: 42, offset: 5021},
							label: "index",
							expr: &ruleRefExpr{
								pos:  position{line: 122, col: 48, offset: 5027},
								name: "RegisterName",
							},
						},
					},
				},
			},
		},
		{
			name: "BaseOnly",
			pos:  position{line: 128, col: 1, offset: 5221},
			expr: &actionExpr{
				pos: position{line: 128, col: 13, offset: 5233},
				run: (*parser).callonBaseOnly1,
				expr: &labeledExpr{
					pos:   position{line: 128, col: 13, offset: 5233},
					label: "base",
					expr: &ruleRefExpr{
						pos:  position{line: 128, col: 18, offset: 5238},
						name: "RegisterName",
					},
				},
			},
		},
		{
			name: "IndexOnly",
			pos:  position{line: 131, col: 1, offset: 5315},
			expr: &actionExpr{
				pos: position{line: 131, col: 14, offset: 5328},
				run: (*parser).callonIndexOnly1,
				expr: &seqExpr{
					pos: position{line: 131, col: 14, offset: 5328},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 131, col: 14, offset: 5328},
							label: "index",
							expr: &ruleRefExpr{
								pos:  position{line: 131, col: 20, offset: 5334},
								name: "RegisterName",
							},
						},
						&labeledExpr{
							pos:   position{line: 131, col: 33, offset: 5347},
							label: "scale",
							expr: &zeroOrOneExpr{
								pos: position{line: 131, col: 39, offset: 5353},
								expr: &ruleRefExpr{
									pos:  position{line: 131, col: 39, offset: 5353},
									name: "Scale",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DispOnly",
			pos:  position{line: 139, col: 1, offset: 5617},
			expr: &actionExpr{
				pos: position{line: 139, col: 13, offset: 5629},
				run: (*parser).callonDispOnly1,
				expr: &labeledExpr{
					pos:   position{line: 139, col: 13, offset: 5629},
					label: "disp",
					expr: &ruleRefExpr{
						pos:  position{line: 139, col: 18, offset: 5634},
						name: "ImmediateValue",
					},
				},
			},
		},
		{
			name: "Scale",
			pos:  position{line: 146, col: 1, offset: 5810},
			expr: &actionExpr{
				pos: position{line: 146, col: 10, offset: 5819},
				run: (*parser).callonScale1,
				expr: &seqExpr{
					pos: position{line: 146, col: 10, offset: 5819},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 146, col: 10, offset: 5819},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 146, col: 12, offset: 5821},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
						&ruleRefExpr{
							pos:  position{line: 146, col: 16, offset: 5825},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 146, col: 18, offset: 5827},
							label: "s",
							expr: &choiceExpr{
								pos: position{line: 146, col: 21, offset: 5830},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 146, col: 21, offset: 5830},
										val:        "1",
										ignoreCase: false,
										want:       "\"1\"",
									},
									&litMatcher{
										pos:        position{line: 146, col: 27, offset: 5836},
										val:        "2",
										ignoreCase: false,
										want:       "\"2\"",
									},
									&litMatcher{
										pos:        position{line: 146, col: 33, offset: 5842},
										val:        "4",
										ignoreCase: false,
										want:       "\"4\"",
									},
									&litMatcher{
										pos:        position{line: 146, col: 39, offset: 5848},
										val:        "8",
										ignoreCase: false,
										want:       "\"8\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AddOp",
			pos:  position{line: 147, col: 1, offset: 5908},
			expr: &actionExpr{
				pos: position{line: 147, col: 10, offset: 5917},
				run: (*parser).callonAddOp1,
				expr: &seqExpr{
					pos: position{line: 147, col: 10, offset: 5917},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 147, col: 10, offset: 5917},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 147, col: 12, offset: 5919},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 147, col: 16, offset: 5923},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 147, col: 16, offset: 5923},
										val:        "+",
										ignoreCase: false,
										want:       "\"+\"",
									},
									&litMatcher{
										pos:        position{line: 147, col: 22, offset: 5929},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 147, col: 27, offset: 5934},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "ImmediateValue",
			pos:  position{line: 148, col: 1, offset: 5992},
			expr: &actionExpr{
				pos: position{line: 148, col: 19, offset: 6010},
				run: (*parser).callonImmediateValue1,
				expr: &labeledExpr{
					pos:   position{line: 148, col: 19, offset: 6010},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 148, col: 24, offset: 6015},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 148, col: 24, offset: 6015},
								name: "HexFactor",
							},
							&ruleRefExpr{
								pos:  position{line: 148, col: 36, offset: 6027},
								name: "NumberFactor",
							},
						},
					},
				},
			},
		},
		{
			name: "Register",
			pos:  position{line: 151, col: 1, offset: 6151},
			expr: &actionExpr{
				pos: position{line: 151, col: 13, offset: 6163},
				run: (*parser).callonRegister1,
				expr: &labeledExpr{
					pos:   position{line: 151, col: 13, offset: 6163},
					label: "r",
					expr: &ruleRefExpr{
						pos:  position{line: 151, col: 15, offset: 6165},
						name: "RegisterName",
					},
				},
			},
		},
		{
			name: "RegisterName",
			pos:  position{line: 158, col: 1, offset: 6556},
			expr: &choiceExpr{
				pos: position{line: 158, col: 17, offset: 6572},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 158, col: 17, offset: 6572},
						name: "GeneralReg",
					},
					&ruleRefExpr{
						pos:  position{line: 158, col: 30, offset: 6585},
						name: "SegmentRegisterName",
					},
					&ruleRefExpr{
						pos:  position{line: 158, col: 52, offset: 6607},
						name: "MMXReg",
					},
					&ruleRefExpr{
						pos:  position{line: 158, col: 61, offset: 6616},
						name: "XMMReg",
					},
					&ruleRefExpr{
						pos:  position{line: 158, col: 70, offset: 6625},
						name: "YMMReg",
					},
					&ruleRefExpr{
						pos:  position{line: 158, col: 79, offset: 6634},
						name: "ControlReg",
					},
					&ruleRefExpr{
						pos:  position{line: 158, col: 92, offset: 6647},
						name: "DebugReg",
					},
					&actionExpr{
						pos: position{line: 158, col: 103, offset: 6658},
						run: (*parser).callonRegisterName9,
						expr: &ruleRefExpr{
							pos:  position{line: 158, col: 103, offset: 6658},
							name: "TestReg",
						},
					},
				},
			},
		},
		{
			name: "GeneralReg",
			pos:  position{line: 160, col: 1, offset: 6727},
			expr: &choiceExpr{
				pos: position{line: 160, col: 14, offset: 6740},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 160, col: 14, offset: 6740},
						val:        "EAX",
						ignoreCase: false,
						want:       "\"EAX\"",
					},
					&litMatcher{
						pos:        position{line: 160, col: 22, offset: 6748},
						val:        "EBX",
						ignoreCase: false,
						want:       "\"EBX\"",
					},
					&litMatcher{
						pos:        position{line: 160, col: 30, offset: 6756},
						val:        "ECX",
						ignoreCase: false,
						want:       "\"ECX\"",
					},
					&litMatcher{
						pos:        position{line: 160, col: 38, offset: 6764},
						val:        "EDX",
						ignoreCase: false,
						want:       "\"EDX\"",
					},
					&litMatcher{
						pos:        position{line: 160, col: 46, offset: 6772},
						val:        "ESI",
						ignoreCase: false,
						want:       "\"ESI\"",
					},
					&litMatcher{
						pos:        position{line: 160, col: 54, offset: 6780},
						val:        "EDI",
						ignoreCase: false,
						want:       "\"EDI\"",
					},
					&litMatcher{
						pos:        position{line: 160, col: 62, offset: 6788},
						val:        "ESP",
						ignoreCase: false,
						want:       "\"ESP\"",
					},
					&litMatcher{
						pos:        position{line: 160, col: 70, offset: 6796},
						val:        "EBP",
						ignoreCase: false,
						want:       "\"EBP\"",
					},
					&litMatcher{
						pos:        position{line: 161, col: 14, offset: 6817},
						val:        "AX",
						ignoreCase: false,
						want:       "\"AX\"",
					},
					&litMatcher{
						pos:        position{line: 161, col: 21, offset: 6824},
						val:        "BX",
						ignoreCase: false,
						want:       "\"BX\"",
					},
					&litMatcher{
						pos:        position{line: 161, col: 28, offset: 6831},
						val:        "CX",
						ignoreCase: false,
						want:       "\"CX\"",
					},
					&litMatcher{
						pos:        position{line: 161, col: 35, offset: 6838},
						val:        "DX",
						ignoreCase: false,
						want:       "\"DX\"",
					},
					&litMatcher{
						pos:        position{line: 161, col: 42, offset: 6845},
						val:        "SI",
						ignoreCase: false,
						want:       "\"SI\"",
					},
					&litMatcher{
						pos:        position{line: 161, col: 49, offset: 6852},
						val:        "DI",
						ignoreCase: false,
						want:       "\"DI\"",
					},
					&litMatcher{
						pos:        position{line: 161, col: 56, offset: 6859},
						val:        "SP",
						ignoreCase: false,
						want:       "\"SP\"",
					},
					&litMatcher{
						pos:        position{line: 161, col: 63, offset: 6866},
						val:        "BP",
						ignoreCase: false,
						want:       "\"BP\"",
					},
					&litMatcher{
						pos:        position{line: 162, col: 14, offset: 6886},
						val:        "AL",
						ignoreCase: false,
						want:       "\"AL\"",
					},
					&litMatcher{
						pos:        position{line: 162, col: 21, offset: 6893},
						val:        "BL",
						ignoreCase: false,
						want:       "\"BL\"",
					},
					&litMatcher{
						pos:        position{line: 162, col: 28, offset: 6900},
						val:        "CL",
						ignoreCase: false,
						want:       "\"CL\"",
					},
					&litMatcher{
						pos:        position{line: 162, col: 35, offset: 6907},
						val:        "DL",
						ignoreCase: false,
						want:       "\"DL\"",
					},
					&litMatcher{
						pos:        position{line: 162, col: 42, offset: 6914},
						val:        "AH",
						ignoreCase: false,
						want:       "\"AH\"",
					},
					&litMatcher{
						pos:        position{line: 162, col: 49, offset: 6921},
						val:        "BH",
						ignoreCase: false,
						want:       "\"BH\"",
					},
					&litMatcher{
						pos:        position{line: 162, col: 56, offset: 6928},
						val:        "CH",
						ignoreCase: false,
						want:       "\"CH\"",
					},
					&litMatcher{
						pos:        position{line: 162, col: 63, offset: 6935},
						val:        "DH",
						ignoreCase: false,
						want:       "\"DH\"",
					},
				},
			},
		},
		{
			name: "SegmentRegisterName",
			pos:  position{line: 163, col: 1, offset: 6940},
			expr: &choiceExpr{
				pos: position{line: 163, col: 23, offset: 6962},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 163, col: 23, offset: 6962},
						val:        "CS",
						ignoreCase: false,
						want:       "\"CS\"",
					},
					&litMatcher{
						pos:        position{line: 163, col: 30, offset: 6969},
						val:        "DS",
						ignoreCase: false,
						want:       "\"DS\"",
					},
					&litMatcher{
						pos:        position{line: 163, col: 37, offset: 6976},
						val:        "ES",
						ignoreCase: false,
						want:       "\"ES\"",
					},
					&litMatcher{
						pos:        position{line: 163, col: 44, offset: 6983},
						val:        "FS",
						ignoreCase: false,
						want:       "\"FS\"",
					},
					&litMatcher{
						pos:        position{line: 163, col: 51, offset: 6990},
						val:        "GS",
						ignoreCase: false,
						want:       "\"GS\"",
					},
					&litMatcher{
						pos:        position{line: 163, col: 58, offset: 6997},
						val:        "SS",
						ignoreCase: false,
						want:       "\"SS\"",
					},
				},
			},
		},
		{
			name: "MMXReg",
			pos:  position{line: 164, col: 1, offset: 7031},
			expr: &choiceExpr{
				pos: position{line: 164, col: 10, offset: 7040},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 164, col: 10, offset: 7040},
						val:        "MM0",
						ignoreCase: false,
						want:       "\"MM0\"",
					},
					&litMatcher{
						pos:        position{line: 164, col: 18, offset: 7048},
						val:        "MM1",
						ignoreCase: false,
						want:       "\"MM1\"",
					},
					&litMatcher{
						pos:        position{line: 164, col: 26, offset: 7056},
						val:        "MM2",
						ignoreCase: false,
						want:       "\"MM2\"",
					},
					&litMatcher{
						pos:        position{line: 164, col: 34, offset: 7064},
						val:        "MM3",
						ignoreCase: false,
						want:       "\"MM3\"",
					},
					&litMatcher{
						pos:        position{line: 164, col: 42, offset: 7072},
						val:        "MM4",
						ignoreCase: false,
						want:       "\"MM4\"",
					},
					&litMatcher{
						pos:        position{line: 164, col: 50, offset: 7080},
						val:        "MM5",
						ignoreCase: false,
						want:       "\"MM5\"",
					},
					&litMatcher{
						pos:        position{line: 164, col: 58, offset: 7088},
						val:        "MM6",
						ignoreCase: false,
						want:       "\"MM6\"",
					},
					&litMatcher{
						pos:        position{line: 164, col: 66, offset: 7096},
						val:        "MM7",
						ignoreCase: false,
						want:       "\"MM7\"",
					},
				},
			},
		},
		{
			name: "XMMReg",
			pos:  position{line: 165, col: 1, offset: 7102},
			expr: &choiceExpr{
				pos: position{line: 165, col: 10, offset: 7111},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 165, col: 10, offset: 7111},
						val:        "XMM0",
						ignoreCase: false,
						want:       "\"XMM0\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 19, offset: 7120},
						val:        "XMM1",
						ignoreCase: false,
						want:       "\"XMM1\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 28, offset: 7129},
						val:        "XMM2",
						ignoreCase: false,
						want:       "\"XMM2\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 37, offset: 7138},
						val:        "XMM3",
						ignoreCase: false,
						want:       "\"XMM3\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 46, offset: 7147},
						val:        "XMM4",
						ignoreCase: false,
						want:       "\"XMM4\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 55, offset: 7156},
						val:        "XMM5",
						ignoreCase: false,
						want:       "\"XMM5\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 64, offset: 7165},
						val:        "XMM6",
						ignoreCase: false,
						want:       "\"XMM6\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 73, offset: 7174},
						val:        "XMM7",
						ignoreCase: false,
						want:       "\"XMM7\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 82, offset: 7183},
						val:        "XMM8",
						ignoreCase: false,
						want:       "\"XMM8\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 91, offset: 7192},
						val:        "XMM9",
						ignoreCase: false,
						want:       "\"XMM9\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 100, offset: 7201},
						val:        "XMM10",
						ignoreCase: false,
						want:       "\"XMM10\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 110, offset: 7211},
						val:        "XMM11",
						ignoreCase: false,
						want:       "\"XMM11\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 120, offset: 7221},
						val:        "XMM12",
						ignoreCase: false,
						want:       "\"XMM12\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 130, offset: 7231},
						val:        "XMM13",
						ignoreCase: false,
						want:       "\"XMM13\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 140, offset: 7241},
						val:        "XMM14",
						ignoreCase: false,
						want:       "\"XMM14\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 150, offset: 7251},
						val:        "XMM15",
						ignoreCase: false,
						want:       "\"XMM15\"",
					},
				},
			},
		},
		{
			name: "YMMReg",
			pos:  position{line: 166, col: 1, offset: 7259},
			expr: &choiceExpr{
				pos: position{line: 166, col: 10, offset: 7268},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 166, col: 10, offset: 7268},
						val:        "YMM0",
						ignoreCase: false,
						want:       "\"YMM0\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 19, offset: 7277},
						val:        "YMM1",
						ignoreCase: false,
						want:       "\"YMM1\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 28, offset: 7286},
						val:        "YMM2",
						ignoreCase: false,
						want:       "\"YMM2\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 37, offset: 7295},
						val:        "YMM3",
						ignoreCase: false,
						want:       "\"YMM3\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 46, offset: 7304},
						val:        "YMM4",
						ignoreCase: false,
						want:       "\"YMM4\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 55, offset: 7313},
						val:        "YMM5",
						ignoreCase: false,
						want:       "\"YMM5\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 64, offset: 7322},
						val:        "YMM6",
						ignoreCase: false,
						want:       "\"YMM6\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 73, offset: 7331},
						val:        "YMM7",
						ignoreCase: false,
						want:       "\"YMM7\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 82, offset: 7340},
						val:        "YMM8",
						ignoreCase: false,
						want:       "\"YMM8\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 91, offset: 7349},
						val:        "YMM9",
						ignoreCase: false,
						want:       "\"YMM9\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 100, offset: 7358},
						val:        "YMM10",
						ignoreCase: false,
						want:       "\"YMM10\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 110, offset: 7368},
						val:        "YMM11",
						ignoreCase: false,
						want:       "\"YMM11\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 120, offset: 7378},
						val:        "YMM12",
						ignoreCase: false,
						want:       "\"YMM12\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 130, offset: 7388},
						val:        "YMM13",
						ignoreCase: false,
						want:       "\"YMM13\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 140, offset: 7398},
						val:        "YMM14",
						ignoreCase: false,
						want:       "\"YMM14\"",
					},
					&litMatcher{
						pos:        position{line: 166, col: 150, offset: 7408},
						val:        "YMM15",
						ignoreCase: false,
						want:       "\"YMM15\"",
					},
				},
			},
		},
		{
			name: "ControlReg",
			pos:  position{line: 167, col: 1, offset: 7416},
			expr: &choiceExpr{
				pos: position{line: 167, col: 14, offset: 7429},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 167, col: 14, offset: 7429},
						val:        "CR0",
						ignoreCase: false,
						want:       "\"CR0\"",
					},
					&litMatcher{
						pos:        position{line: 167, col: 22, offset: 7437},
						val:        "CR1",
						ignoreCase: false,
						want:       "\"CR1\"",
					},
					&litMatcher{
						pos:        position{line: 167, col: 30, offset: 7445},
						val:        "CR2",
						ignoreCase: false,
						want:       "\"CR2\"",
					},
					&litMatcher{
						pos:        position{line: 167, col: 38, offset: 7453},
						val:        "CR3",
						ignoreCase: false,
						want:       "\"CR3\"",
					},
					&litMatcher{
						pos:        position{line: 167, col: 46, offset: 7461},
						val:        "CR4",
						ignoreCase: false,
						want:       "\"CR4\"",
					},
					&litMatcher{
						pos:        position{line: 167, col: 54, offset: 7469},
						val:        "CR5",
						ignoreCase: false,
						want:       "\"CR5\"",
					},
					&litMatcher{
						pos:        position{line: 167, col: 62, offset: 7477},
						val:        "CR6",
						ignoreCase: false,
						want:       "\"CR6\"",
					},
					&litMatcher{
						pos:        position{line: 167, col: 70, offset: 7485},
						val:        "CR7",
						ignoreCase: false,
						want:       "\"CR7\"",
					},
					&litMatcher{
						pos:        position{line: 167, col: 78, offset: 7493},
						val:        "CR8",
						ignoreCase: false,
						want:       "\"CR8\"",
					},
				},
			},
		},
		{
			name: "DebugReg",
			pos:  position{line: 168, col: 1, offset: 7499},
			expr: &choiceExpr{
				pos: position{line: 168, col: 12, offset: 7510},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 168, col: 12, offset: 7510},
						val:        "DR0",
						ignoreCase: false,
						want:       "\"DR0\"",
					},
					&litMatcher{
						pos:        position{line: 168, col: 20, offset: 7518},
						val:        "DR1",
						ignoreCase: false,
						want:       "\"DR1\"",
					},
					&litMatcher{
						pos:        position{line: 168, col: 28, offset: 7526},
						val:        "DR2",
						ignoreCase: false,
						want:       "\"DR2\"",
					},
					&litMatcher{
						pos:        position{line: 168, col: 36, offset: 7534},
						val:        "DR3",
						ignoreCase: false,
						want:       "\"DR3\"",
					},
					&litMatcher{
						pos:        position{line: 168, col: 44, offset: 7542},
						val:        "DR4",
						ignoreCase: false,
						want:       "\"DR4\"",
					},
					&litMatcher{
						pos:        position{line: 168, col: 52, offset: 7550},
						val:        "DR5",
						ignoreCase: false,
						want:       "\"DR5\"",
					},
					&litMatcher{
						pos:        position{line: 168, col: 60, offset: 7558},
						val:        "DR6",
						ignoreCase: false,
						want:       "\"DR6\"",
					},
					&litMatcher{
						pos:        position{line: 168, col: 68, offset: 7566},
						val:        "DR7",
						ignoreCase: false,
						want:       "\"DR7\"",
					},
				},
			},
		},
		{
			name: "TestReg",
			pos:  position{line: 169, col: 1, offset: 7572},
			expr: &choiceExpr{
				pos: position{line: 169, col: 11, offset: 7582},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 169, col: 11, offset: 7582},
						val:        "TR0",
						ignoreCase: false,
						want:       "\"TR0\"",
					},
					&litMatcher{
						pos:        position{line: 169, col: 19, offset: 7590},
						val:        "TR1",
						ignoreCase: false,
						want:       "\"TR1\"",
					},
					&litMatcher{
						pos:        position{line: 169, col: 27, offset: 7598},
						val:        "TR2",
						ignoreCase: false,
						want:       "\"TR2\"",
					},
					&litMatcher{
						pos:        position{line: 169, col: 35, offset: 7606},
						val:        "TR3",
						ignoreCase: false,
						want:       "\"TR3\"",
					},
					&litMatcher{
						pos:        position{line: 169, col: 43, offset: 7614},
						val:        "TR4",
						ignoreCase: false,
						want:       "\"TR4\"",
					},
					&litMatcher{
						pos:        position{line: 169, col: 51, offset: 7622},
						val:        "TR5",
						ignoreCase: false,
						want:       "\"TR5\"",
					},
					&litMatcher{
						pos:        position{line: 169, col: 59, offset: 7630},
						val:        "TR6",
						ignoreCase: false,
						want:       "\"TR6\"",
					},
					&litMatcher{
						pos:        position{line: 169, col: 67, offset: 7638},
						val:        "TR7",
						ignoreCase: false,
						want:       "\"TR7\"",
					},
				},
			},
		},
		{
			name: "Immediate",
			pos:  position{line: 173, col: 1, offset: 7667},
			expr: &actionExpr{
				pos: position{line: 173, col: 14, offset: 7680},
				run: (*parser).callonImmediate1,
				expr: &labeledExpr{
					pos:   position{line: 173, col: 14, offset: 7680},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 173, col: 19, offset: 7685},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 173, col: 19, offset: 7685},
								name: "HexFactor",
							},
							&ruleRefExpr{
								pos:  position{line: 173, col: 31, offset: 7697},
								name: "NumberFactor",
							},
							&ruleRefExpr{
								pos:  position{line: 173, col: 46, offset: 7712},
								name: "CharFactor",
							},
						},
					},
				},
			},
		},
		{
			name: "HexFactor",
			pos:  position{line: 182, col: 1, offset: 8103},
			expr: &actionExpr{
				pos: position{line: 182, col: 14, offset: 8116},
				run: (*parser).callonHexFactor1,
				expr: &seqExpr{
					pos: position{line: 182, col: 14, offset: 8116},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 182, col: 14, offset: 8116},
							val:        "0",
							ignoreCase: false,
							want:       "\"0\"",
						},
						&choiceExpr{
							pos: position{line: 182, col: 19, offset: 8121},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 182, col: 19, offset: 8121},
									val:        "x",
									ignoreCase: false,
									want:       "\"x\"",
								},
								&litMatcher{
									pos:        position{line: 182, col: 25, offset: 8127},
									val:        "X",
									ignoreCase: false,
									want:       "\"X\"",
								},
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 182, col: 30, offset: 8132},
							expr: &charClassMatcher{
								pos:        position{line: 182, col: 30, offset: 8132},
								val:        "[0-9a-fA-F]",
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "NumberFactor",
			pos:  position{line: 183, col: 1, offset: 8205},
			expr: &actionExpr{
				pos: position{line: 183, col: 17, offset: 8221},
				run: (*parser).callonNumberFactor1,
				expr: &seqExpr{
					pos: position{line: 183, col: 17, offset: 8221},
					exprs: []any{
						&zeroOrOneExpr{
							pos: position{line: 183, col: 17, offset: 8221},
							expr: &litMatcher{
								pos:        position{line: 183, col: 17, offset: 8221},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 183, col: 22, offset: 8226},
							expr: &charClassMatcher{
								pos:        position{line: 183, col: 22, offset: 8226},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "CharFactor",
			pos:  position{line: 185, col: 1, offset: 8425},
			expr: &actionExpr{
				pos: position{line: 185, col: 15, offset: 8439},
				run: (*parser).callonCharFactor1,
				expr: &seqExpr{
					pos: position{line: 185, col: 15, offset: 8439},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 185, col: 15, offset: 8439},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
						&labeledExpr{
							pos:   position{line: 185, col: 20, offset: 8444},
							label: "charVal",
							expr: &charClassMatcher{
								pos:        position{line: 185, col: 28, offset: 8452},
								val:        "[^']",
								chars:      []rune{'\''},
								ignoreCase: false,
								inverted:   true,
							},
						},
						&litMatcher{
							pos:        position{line: 185, col: 33, offset: 8457},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
					},
				},
			},
		},
		{
			name: "Label",
			pos:  position{line: 196, col: 1, offset: 8854},
			expr: &actionExpr{
				pos: position{line: 196, col: 10, offset: 8863},
				run: (*parser).callonLabel1,
				expr: &labeledExpr{
					pos:   position{line: 196, col: 10, offset: 8863},
					label: "l",
					expr: &ruleRefExpr{
						pos:  position{line: 196, col: 12, offset: 8865},
						name: "IdentFactor",
					},
				},
			},
		},
		{
			name: "IdentFactor",
			pos:  position{line: 202, col: 1, offset: 9198},
			expr: &actionExpr{
				pos: position{line: 202, col: 16, offset: 9213},
				run: (*parser).callonIdentFactor1,
				expr: &seqExpr{
					pos: position{line: 202, col: 16, offset: 9213},
					exprs: []any{
						&notExpr{
							pos: position{line: 202, col: 16, offset: 9213},
							expr: &ruleRefExpr{
								pos:  position{line: 202, col: 17, offset: 9214},
								name: "ReservedWord",
							},
						},
						&notExpr{
							pos: position{line: 202, col: 30, offset: 9227},
							expr: &ruleRefExpr{
								pos:  position{line: 202, col: 31, offset: 9228},
								name: "RegisterName",
							},
						},
						&charClassMatcher{
							pos:        position{line: 202, col: 44, offset: 9241},
							val:        "[a-zA-Z$_.]",
							chars:      []rune{'$', '_', '.'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 202, col: 56, offset: 9253},
							expr: &charClassMatcher{
								pos:        position{line: 202, col: 56, offset: 9253},
								val:        "[a-zA-Z$_.0-9]",
								chars:      []rune{'$', '_', '.'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "SegmentRegister",
			pos:  position{line: 205, col: 1, offset: 9429},
			expr: &actionExpr{
				pos: position{line: 205, col: 20, offset: 9448},
				run: (*parser).callonSegmentRegister1,
				expr: &labeledExpr{
					pos:   position{line: 205, col: 20, offset: 9448},
					label: "r",
					expr: &ruleRefExpr{
						pos:  position{line: 205, col: 22, offset: 9450},
						name: "SegmentRegisterName",
					},
				},
			},
		},
		{
			name: "DataType",
			pos:  position{line: 211, col: 1, offset: 9655},
			expr: &choiceExpr{
				pos: position{line: 211, col: 12, offset: 9666},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 211, col: 12, offset: 9666},
						val:        "BYTE",
						ignoreCase: false,
						want:       "\"BYTE\"",
					},
					&litMatcher{
						pos:        position{line: 211, col: 21, offset: 9675},
						val:        "WORD",
						ignoreCase: false,
						want:       "\"WORD\"",
					},
					&actionExpr{
						pos: position{line: 211, col: 30, offset: 9684},
						run: (*parser).callonDataType4,
						expr: &litMatcher{
							pos:        position{line: 211, col: 30, offset: 9684},
							val:        "DWORD",
							ignoreCase: false,
							want:       "\"DWORD\"",
						},
					},
				},
			},
		},
		{
			name: "JumpType",
			pos:  position{line: 212, col: 1, offset: 9752},
			expr: &choiceExpr{
				pos: position{line: 212, col: 12, offset: 9763},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 212, col: 12, offset: 9763},
						val:        "SHORT",
						ignoreCase: false,
						want:       "\"SHORT\"",
					},
					&litMatcher{
						pos:        position{line: 212, col: 22, offset: 9773},
						val:        "NEAR",
						ignoreCase: false,
						want:       "\"NEAR\"",
					},
					&actionExpr{
						pos: position{line: 212, col: 31, offset: 9782},
						run: (*parser).callonJumpType4,
						expr: &litMatcher{
							pos:        position{line: 212, col: 31, offset: 9782},
							val:        "FAR",
							ignoreCase: false,
							want:       "\"FAR\"",
						},
					},
				},
			},
		},
		{
			name: "ReservedWord",
			pos:  position{line: 213, col: 1, offset: 9848},
			expr: &choiceExpr{
				pos: position{line: 213, col: 16, offset: 9863},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 213, col: 16, offset: 9863},
						name: "DataType",
					},
					&ruleRefExpr{
						pos:  position{line: 213, col: 27, offset: 9874},
						name: "JumpType",
					},
					&litMatcher{
						pos:        position{line: 213, col: 38, offset: 9885},
						val:        "PTR",
						ignoreCase: false,
						want:       "\"PTR\"",
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 216, col: 1, offset: 9958},
			expr: &zeroOrMoreExpr{
				pos: position{line: 216, col: 6, offset: 9963},
				expr: &charClassMatcher{
					pos:        position{line: 216, col: 6, offset: 9963},
					val:        "[ \\t\\n\\r]",
					chars:      []rune{' ', '\t', '\n', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 217, col: 1, offset: 9974},
			expr: &notExpr{
				pos: position{line: 217, col: 8, offset: 9981},
				expr: &anyMatcher{
					line: 217, col: 9, offset: 9982,
				},
			},
		},
	},
}

func (c *current) onOperandString1(op any) (any, error) {
	// パース結果を ParsedOperandPeg に設定
	operand := op.(*ParsedOperandPeg)
	operand.RawString = string(c.text) // 元の文字列を保持
	return operand, nil
}

func (p *parser) callonOperandString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperandString1(stack["op"])
}

func (c *current) onMemoryAddress1(dt, jt, seg, body any) (any, error) {
	// Add spaces after DataType and JumpType
	memInfo := body.(*MemoryInfo)
	var dataType ast.DataType // ast.DataType を使用
	if dt != nil {
		dtStr := string(dt.([]byte))
		dataType, _ = ast.NewDataType(dtStr) // ast.NewDataType を使用
	}
	var jumpType string
	if jt != nil {
		jumpType = string(jt.([]byte))
	}

	if seg != nil {
		// seg は []any{[]byte("ES"), _, []byte(":"), _} のような形になる
		segBytes := seg.([]any)[0].([]byte)
		memInfo.Segment = string(segBytes) // セグメントオーバーライド
	}
	return &ParsedOperandPeg{
		Type:     CodeM, // 仮: 型は後で詳細化
		Memory:   memInfo,
		DataType: dataType,
		JumpType: jumpType,
	}, nil
}

func (p *parser) callonMemoryAddress1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMemoryAddress1(stack["dt"], stack["jt"], stack["seg"], stack["body"])
}

func (c *current) onBaseIndexScaleDisp1(base, op1, index, scale, op2, disp any) (any, error) {
	baseReg := string(base.([]byte))
	indexReg := string(index.([]byte))
	scaleVal, _ := strconv.Atoi(string(scale.([]byte)))
	dispVal := toInt(string(disp.([]byte)))
	isHex := isHex(string(disp.([]byte)))
	if string(op1.([]byte)) == "-" { /* index の符号は通常+ */
	}
	if string(op2.([]byte)) == "-" {
		dispVal = -dispVal
	}
	return &MemoryInfo{BaseReg: baseReg, IndexReg: indexReg, Scale: scaleVal, Displacement: dispVal, IsHexDisp: isHex}, nil
}

func (p *parser) callonBaseIndexScaleDisp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBaseIndexScaleDisp1(stack["base"], stack["op1"], stack["index"], stack["scale"], stack["op2"], stack["disp"])
}

func (c *current) onBaseIndexDisp1(base, op1, index, op2, disp any) (any, error) {
	baseReg := string(base.([]byte))
	indexReg := string(index.([]byte))
	dispVal := toInt(string(disp.([]byte)))
	isHex := isHex(string(disp.([]byte)))
	if string(op1.([]byte)) == "-" { /* index の符号は通常+ */
	}
	if string(op2.([]byte)) == "-" {
		dispVal = -dispVal
	}
	return &MemoryInfo{BaseReg: baseReg, IndexReg: indexReg, Scale: 1, Displacement: dispVal, IsHexDisp: isHex}, nil
}

func (p *parser) callonBaseIndexDisp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBaseIndexDisp1(stack["base"], stack["op1"], stack["index"], stack["op2"], stack["disp"])
}

func (c *current) onBaseScaleDisp1(base, op1, index, scale any) (any, error) {
	// Dispなしのパターン (例: [EAX+EBX*4])
	baseReg := string(base.([]byte))
	indexReg := string(index.([]byte))
	scaleVal, _ := strconv.Atoi(string(scale.([]byte)))
	return &MemoryInfo{BaseReg: baseReg, IndexReg: indexReg, Scale: scaleVal}, nil
}

func (p *parser) callonBaseScaleDisp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBaseScaleDisp1(stack["base"], stack["op1"], stack["index"], stack["scale"])
}

func (c *current) onIndexScaleDisp1(index, scale, op1, disp any) (any, error) {
	indexReg := string(index.([]byte))
	scaleVal, _ := strconv.Atoi(string(scale.([]byte)))
	dispVal := toInt(string(disp.([]byte)))
	isHex := isHex(string(disp.([]byte)))
	if string(op1.([]byte)) == "-" {
		dispVal = -dispVal
	}
	return &MemoryInfo{IndexReg: indexReg, Scale: scaleVal, Displacement: dispVal, IsHexDisp: isHex}, nil
}

func (p *parser) callonIndexScaleDisp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexScaleDisp1(stack["index"], stack["scale"], stack["op1"], stack["disp"])
}

func (c *current) onBaseDisp1(base, op1, disp any) (any, error) {
	baseReg := string(base.([]byte))
	dispVal := toInt(string(disp.([]byte)))
	isHex := isHex(string(disp.([]byte)))
	if string(op1.([]byte)) == "-" {
		dispVal = -dispVal
	}
	return &MemoryInfo{BaseReg: baseReg, Displacement: dispVal, IsHexDisp: isHex}, nil
}

func (p *parser) callonBaseDisp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBaseDisp1(stack["base"], stack["op1"], stack["disp"])
}

func (c *current) onIndexDisp1(index, op1, disp any) (any, error) {
	// Baseなし、Indexあり、Dispあり
	indexReg := string(index.([]byte))
	dispVal := toInt(string(disp.([]byte)))
	isHex := isHex(string(disp.([]byte)))
	if string(op1.([]byte)) == "-" {
		dispVal = -dispVal
	}
	return &MemoryInfo{IndexReg: indexReg, Scale: 1, Displacement: dispVal, IsHexDisp: isHex}, nil
}

func (p *parser) callonIndexDisp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexDisp1(stack["index"], stack["op1"], stack["disp"])
}

func (c *current) onBaseIndex1(base, op1, index any) (any, error) {
	baseReg := string(base.([]byte))
	indexReg := string(index.([]byte))
	// op1 は通常 '+'
	return &MemoryInfo{BaseReg: baseReg, IndexReg: indexReg, Scale: 1}, nil
}

func (p *parser) callonBaseIndex1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBaseIndex1(stack["base"], stack["op1"], stack["index"])
}

func (c *current) onBaseOnly1(base any) (any, error) {
	return &MemoryInfo{BaseReg: string(base.([]byte))}, nil
}

func (p *parser) callonBaseOnly1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBaseOnly1(stack["base"])
}

func (c *current) onIndexOnly1(index, scale any) (any, error) {
	// Indexのみ、Scaleはオプショナル
	indexReg := string(index.([]byte))
	scaleVal := 1
	if scale != nil {
		scaleVal, _ = strconv.Atoi(string(scale.([]byte)))
	}
	return &MemoryInfo{IndexReg: indexReg, Scale: scaleVal}, nil
}

func (p *parser) callonIndexOnly1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexOnly1(stack["index"], stack["scale"])
}

func (c *current) onDispOnly1(disp any) (any, error) {
	dispVal := toInt(string(disp.([]byte)))
	isHex := isHex(string(disp.([]byte)))
	return &MemoryInfo{Displacement: dispVal, IsHexDisp: isHex}, nil
}

func (p *parser) callonDispOnly1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDispOnly1(stack["disp"])
}

func (c *current) onScale1(s any) (any, error) {
	return s, nil
}

func (p *parser) callonScale1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScale1(stack["s"])
}

func (c *current) onAddOp1(op any) (any, error) {
	return op, nil
}

func (p *parser) callonAddOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddOp1(stack["op"])
}

func (c *current) onImmediateValue1(val any) (any, error) {
	return val, nil
}

func (p *parser) callonImmediateValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onImmediateValue1(stack["val"])
}

func (c *current) onRegister1(r any) (any, error) {
	regName := string(r.([]byte))
	// レジスタの種類に応じて Type を設定 (CodeR8, CodeR16, CodeR32, CodeSREG など)
	regType := getRegisterType(regName) // getRegisterType は operand_types.go で定義想定
	return &ParsedOperandPeg{Type: regType, Register: regName}, nil
}

func (p *parser) callonRegister1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegister1(stack["r"])
}

func (c *current) onRegisterName9() (any, error) {
	return c.text, nil
}

func (p *parser) callonRegisterName9() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegisterName9()
}

func (c *current) onImmediate1(val any) (any, error) {
	immStr := string(val.([]byte)) // val は []byte
	value := toInt(immStr)
	hex := isHex(immStr)
	// 即値のサイズに応じて Type を設定 (CodeIMM8, CodeIMM16, CodeIMM32)
	immType := getImmediateSizeType(value) // getImmediateSizeType は operand_types.go で定義想定
	return &ParsedOperandPeg{Type: immType, Immediate: value, IsHex: hex}, nil
}

func (p *parser) callonImmediate1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onImmediate1(stack["val"])
}

func (c *current) onHexFactor1() (any, error) {
	return c.text, nil
}

func (p *parser) callonHexFactor1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHexFactor1()
}

func (c *current) onNumberFactor1() (any, error) {
	return c.text, nil
}

func (p *parser) callonNumberFactor1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumberFactor1()
}

func (c *current) onCharFactor1(charVal any) (any, error) {
	// 'A' -> 65 のように文字コード (int64) を返す
	charByte := charVal.([]byte)
	if len(charByte) != 1 {
		// エラー処理: シングルクォート内は1文字のみ許容
		return nil, failure.New(failure.StringCode("ParseError"), failure.Messagef("invalid char factor: %s", string(c.text)))
	}
	return int64(charByte[0]), nil
}

func (p *parser) callonCharFactor1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharFactor1(stack["charVal"])
}

func (c *current) onLabel1(l any) (any, error) {
	labelName := string(l.([]byte))
	// ラベルのタイプ (REL8, REL16, REL32, IMM) はここでは決定せず、
	// 後続の処理 (asmdb検索など) で決定する想定。一旦 CodeLABEL などにするか？
	return &ParsedOperandPeg{Type: CodeLABEL, Label: labelName}, nil // CodeLABEL は仮
}

func (p *parser) callonLabel1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLabel1(stack["l"])
}

func (c *current) onIdentFactor1() (any, error) {
	return c.text, nil
}

func (p *parser) callonIdentFactor1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentFactor1()
}

func (c *current) onSegmentRegister1(r any) (any, error) {
	segName := string(r.([]byte))
	return &ParsedOperandPeg{Type: CodeSREG, Segment: segName}, nil
}

func (p *parser) callonSegmentRegister1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSegmentRegister1(stack["r"])
}

func (c *current) onDataType4() (any, error) {
	return c.text, nil
}

func (p *parser) callonDataType4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDataType4()
}

func (c *current) onJumpType4() (any, error) {
	return c.text, nil
}

func (p *parser) callonJumpType4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onJumpType4()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
