// Code generated by github.com/Bin-Huang/newc; DO NOT EDIT.

package ast

// NewNumberFactor Create a new NumberFactor
func NewNumberFactor(baseFactor BaseFactor, value int) *NumberFactor {
	return &NumberFactor{
		BaseFactor: baseFactor,
		value:      value,
	}
}

// NewStringFactor Create a new StringFactor
func NewStringFactor(baseFactor BaseFactor, value string) *StringFactor {
	return &StringFactor{
		BaseFactor: baseFactor,
		value:      value,
	}
}

// NewHexFactor Create a new HexFactor
func NewHexFactor(baseFactor BaseFactor, value string) *HexFactor {
	return &HexFactor{
		BaseFactor: baseFactor,
		value:      value,
	}
}

// NewIdentFactor Create a new IdentFactor
func NewIdentFactor(baseFactor BaseFactor, value string) *IdentFactor {
	return &IdentFactor{
		BaseFactor: baseFactor,
		value:      value,
	}
}

// NewCharFactor Create a new CharFactor
func NewCharFactor(baseFactor BaseFactor, value string) *CharFactor {
	return &CharFactor{
		BaseFactor: baseFactor,
		value:      value,
	}
}
