// Code generated by github.com/Bin-Huang/newc; DO NOT EDIT.

package ast

// NewPlusExp Create a new PlusExp
func NewPlusExp(baseExp BaseExp, exp1 Exp, exp2 Exp) *PlusExp {
	return &PlusExp{
		BaseExp: baseExp,
		Exp1:    exp1,
		Exp2:    exp2,
	}
}

// NewImmExp Create a new ImmExp
func NewImmExp(baseExp BaseExp, factor Factor) *ImmExp {
	return &ImmExp{
		BaseExp: baseExp,
		Factor:  factor,
	}
}

// NewNumberFactor Create a new NumberFactor
func NewNumberFactor(baseFactor BaseFactor, value int) *NumberFactor {
	return &NumberFactor{
		BaseFactor: baseFactor,
		Value:      value,
	}
}

// NewStringFactor Create a new StringFactor
func NewStringFactor(baseFactor BaseFactor, value string) *StringFactor {
	return &StringFactor{
		BaseFactor: baseFactor,
		Value:      value,
	}
}

// NewHexFactor Create a new HexFactor
func NewHexFactor(baseFactor BaseFactor, value string) *HexFactor {
	return &HexFactor{
		BaseFactor: baseFactor,
		Value:      value,
	}
}

// NewIdentFactor Create a new IdentFactor
func NewIdentFactor(baseFactor BaseFactor, value string) *IdentFactor {
	return &IdentFactor{
		BaseFactor: baseFactor,
		Value:      value,
	}
}

// NewCharFactor Create a new CharFactor
func NewCharFactor(baseFactor BaseFactor, value string) *CharFactor {
	return &CharFactor{
		BaseFactor: baseFactor,
		Value:      value,
	}
}

// NewDeclareStmt Create a new DeclareStmt
func NewDeclareStmt(baseStatement BaseStatement, identFactor *IdentFactor, exp Exp) *DeclareStmt {
	return &DeclareStmt{
		BaseStatement: baseStatement,
		IdentFactor:   identFactor,
		Exp:           exp,
	}
}

// NewLabelStmt Create a new LabelStmt
func NewLabelStmt(baseStatement BaseStatement, identFactor *IdentFactor) *LabelStmt {
	return &LabelStmt{
		BaseStatement: baseStatement,
		IdentFactor:   identFactor,
	}
}
