// Code generated by github.com/Bin-Huang/newc; DO NOT EDIT.

package ast

// NewPlusExp Create a new PlusExp
func NewPlusExp(baseExp BaseExp, exp1 Exp, exp2 Exp) *PlusExp {
	return &PlusExp{
		BaseExp: baseExp,
		Exp1:    exp1,
		Exp2:    exp2,
	}
}

// NewImmExp Create a new ImmExp
func NewImmExp(baseExp BaseExp, factor Factor) *ImmExp {
	return &ImmExp{
		BaseExp: baseExp,
		Factor:  factor,
	}
}

// NewNumberFactor Create a new NumberFactor
func NewNumberFactor(baseFactor BaseFactor, value int) *NumberFactor {
	return &NumberFactor{
		BaseFactor: baseFactor,
		Value:      value,
	}
}

// NewStringFactor Create a new StringFactor
func NewStringFactor(baseFactor BaseFactor, value string) *StringFactor {
	return &StringFactor{
		BaseFactor: baseFactor,
		Value:      value,
	}
}

// NewHexFactor Create a new HexFactor
func NewHexFactor(baseFactor BaseFactor, value string) *HexFactor {
	return &HexFactor{
		BaseFactor: baseFactor,
		Value:      value,
	}
}

// NewIdentFactor Create a new IdentFactor
func NewIdentFactor(baseFactor BaseFactor, value string) *IdentFactor {
	return &IdentFactor{
		BaseFactor: baseFactor,
		Value:      value,
	}
}

// NewCharFactor Create a new CharFactor
func NewCharFactor(baseFactor BaseFactor, value string) *CharFactor {
	return &CharFactor{
		BaseFactor: baseFactor,
		Value:      value,
	}
}

// NewDeclareStmt Create a new DeclareStmt
func NewDeclareStmt(baseStatement BaseStatement, id *IdentFactor, value Exp) *DeclareStmt {
	return &DeclareStmt{
		BaseStatement: baseStatement,
		Id:            id,
		Value:         value,
	}
}

// NewLabelStmt Create a new LabelStmt
func NewLabelStmt(baseStatement BaseStatement, label *IdentFactor) *LabelStmt {
	return &LabelStmt{
		BaseStatement: baseStatement,
		Label:         label,
	}
}

// NewExportSymStmt Create a new ExportSymStmt
func NewExportSymStmt(baseStatement BaseStatement, symbols []*IdentFactor) *ExportSymStmt {
	return &ExportSymStmt{
		BaseStatement: baseStatement,
		Symbols:       symbols,
	}
}

// NewExternSymStmt Create a new ExternSymStmt
func NewExternSymStmt(baseStatement BaseStatement, symbols []*IdentFactor) *ExternSymStmt {
	return &ExternSymStmt{
		BaseStatement: baseStatement,
		Symbols:       symbols,
	}
}

// NewConfigStmt Create a new ConfigStmt
func NewConfigStmt(baseStatement BaseStatement, configType ConfigType, factor Factor) *ConfigStmt {
	return &ConfigStmt{
		BaseStatement: baseStatement,
		ConfigType:    configType,
		Factor:        factor,
	}
}

// NewMnemonicStmt Create a new MnemonicStmt
func NewMnemonicStmt(baseStatement BaseStatement, opcode *IdentFactor, mnemonicArgs []Exp) *MnemonicStmt {
	return &MnemonicStmt{
		BaseStatement: baseStatement,
		Opcode:        opcode,
		MnemonicArgs:  mnemonicArgs,
	}
}
